version: 2.1
jobs:
  build:
    docker:
      - image: flatironschool/phoeyonce-student-ide:latest
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            bundle
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'

