version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            bundle
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo 'It worked.'

